export const IDENTIFIERS = {
    AUTH_MIDDLEWARE: 'AUTH_MIDDLEWARE',
    DB_CONNECTION_STRING: 'DB_CONNECTION_STRING',
    DB_USERNAME: 'DB_USERNAME',
    DB_PASSWORD: 'DB_PASSWORD',
    REPOSITORY: 'REPOSITORY',
    UUID_GENERATOR: 'UUID_GENERATOR',
    ORM: 'ORM',
    SERVER: 'SERVER',
};
